# 客户端配置

[server]
remote_server = "127.0.0.1"
remote_port = 1080

[local]
listen_addr = "127.0.0.1"
listen_port = 1081

[logging]
level = "debug"
log_dir = "./logs"

[auth]
enabled = true
shared_secret = "my_secret_key_12345"
username = "client"
sequence = 1
max_time_diff_secs = 60
